language: python
python:
  - "3.7"
cache:
  directories:
    - $PIP_CACHE_DIR
    - $PIPENV_CACHE_DIR
env:
  global:
    - PIP_CACHE_DIR=$HOME/.cache/pip
    - PIPENV_CACHE_DIR=$HOME/.cache/pipenv
install:
  - pip install git+https://github.com/pypa/pipenv.git
  - pipenv install --dev --system
script:
  - black --check .
  - mypy .
  - pytest