language: python
python:
  - "3.7"
cache:
  directories:
    - $PIP_CACHE_DIR
env:
  global:
    - PIP_CACHE_DIR=$HOME/.cache/pip
install:
  - pip install poetry
  - poetry config virtualenvs.create false
  - poetry install --no-interaction
script:
  - black --check .
  - mypy .
  - pytest