version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  frontend:
    build:
      context: .
      dockerfile: docker/frontend/local/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
    env_file:
      - ./.env

  postgres:
    build:
      context: .
      dockerfile: docker/persistence/Dockerfile
    image: stilio_production_postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups
    ports:
      - "5432:5432"
    env_file:
      - ./.env