version: '3'

services:
  crawler:
    build:
      context: .
      dockerfile: compose/crawler/Dockerfile
    network_mode: "host"
    ports:
      - "6881:6881"
    volumes:
      - ./data:/usr/src/app/data
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  frontend:
    build:
      context: .
      dockerfile: compose/frontend/production/Dockerfile
    depends_on:
      - crawler
    ports:
      - "8000:8000"
    volumes:
      - ./data:/usr/src/app/data
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"