version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}


services:
  crawler:
    build:
      context: .
      dockerfile: compose/crawler/Dockerfile
    depends_on:
      - postgres
    network_mode: "host"
    ports:
      - "6881:6881"
    volumes:
      - ./data:/usr/src/app/data
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "200k"

  frontend:
    build:
      context: .
      dockerfile: compose/frontend/production/Dockerfile
    depends_on:
      - crawler
      - postgres
    ports:
      - "80:8000"
    volumes:
      - ./data:/usr/src/app/data
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "200k"

  postgres:
    build:
      context: .
      dockerfile: ./compose/persistence/Dockerfile
    image: stilio_production_postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "200k"
    env_file:
      - ./.env