version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}


services:
  crawler:
    build:
      context: .
      dockerfile: compose/crawler/Dockerfile
    depends_on:
      - postgres
    network_mode: "host"
    ports:
      - "6881:6881"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "200k"
    env_file:
      - ./.env
    environment:
      POSTGRES_HOST: "localhost"
    command: /start

  frontend:
    build:
      context: .
      dockerfile: compose/frontend/production/Dockerfile
    depends_on:
      - postgres
      - crawler
    ports:
      - "80:8000"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "200k"
    env_file:
      - ./.env
    command: gunicorn -k uvicorn.workers.UvicornWorker -b 0.0.0.0:8000 stilio.frontend.main:app

  postgres:
    build:
      context: .
      dockerfile: ./compose/persistence/Dockerfile
    image: stilio_production_postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups
    ports:
      - "5432:5432"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "200k"
    env_file:
      - ./.env